//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class SQLSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static SQLSettings defaultInstance = ((SQLSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SQLSettings())));
        
        public static SQLSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("insert into kcaltable(name,date,kcalDay) values (:p,:p_d,:p_k)")]
        public string CalorieInsert {
            get {
                return ((string)(this["CalorieInsert"]));
            }
            set {
                this["CalorieInsert"] = value;
            }
        }
    }
}
